# docker-compose.yml
version: '3.7'

services:
  auth:
    container_name: auth
    build:
      context: ./ecommerce/auth
    ports:
      - "8000:8000"

  users:
    container_name: users
    build:
      context: ./ecommerce/users
    ports:
      - "8001:8001"
  
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password


  products:
    container_name: products
    build:
      context: ./ecommerce/products
    ports:
      - "8002:3000"  # Asegúrate de que el puerto 3000 coincide con el puerto en el que corre NestJS
    depends_on:
      - postgres

  # order_service:
  #   build:
  #     context: ./ecommerce/order_service
  #   ports:
  #     - "8002:8003"

  # api_gateway:
  #   image: nginx:latest
  #   volumes:
  #     - ./ecommerce/api_gateway/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - auth
  #     - users
  #     # - product_service
  #     # - order_service
  
  